name: Trivy Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  trivy:
    name: Trivy - Repo e Imagem
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Trivy - Scan do repositório
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 0

      - name: Trivy - Scan da imagem MySQL
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: mysql:8.3
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 0
          skip-setup-trivy: true